// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0db2cec6a51bfbc8 "AM portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary' | 'mobile' // Variant
 * title1?: string // Title 1
 * discription1?: string // discription 1
 * title2?: string // Title 2
 * discription2?: string // discription 2
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-YTM2CAUE.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { routes } from "./chunks/chunk-23HYNGZD.js";

// virtual:benefit-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wmE787IEDtCo5j1urISQ/ksczH9YeZdCSOMnkAQ1p/yLuNtHpsx.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/imtSiRaqNXeJxLGmxeu5/MRYsGG3HejYmmn0H66dm/HglFp_qS2.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Plus Jakarta Sans-600",
	"GF;Plus Jakarta Sans-700",
	"GF;Plus Jakarta Sans-700italic",
	"GF;Plus Jakarta Sans-600italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Plus Jakarta Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/plusjakartasans/v8/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_d0nNTxXUEKi4Rw.woff2",
				weight: "600",
			},
			{
				family: "Plus Jakarta Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/plusjakartasans/v8/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/plusjakartasans/v8/LDIZaomQNQcsA88c7O9yZ4KMCoOg4KozySKCdSNG9OcqYQ3CDh_VMq2oR82k.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/plusjakartasans/v8/LDIZaomQNQcsA88c7O9yZ4KMCoOg4KozySKCdSNG9OcqYQ37Dh_VMq2oR82k.woff2",
				weight: "600",
			},
		],
	},
];
var css2 = [
	'.framer-UddiK .framer-styles-preset-1o2kbzs:not(.rich-text-wrapper), .framer-UddiK .framer-styles-preset-1o2kbzs.rich-text-wrapper h4 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 25px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 600; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1299px) and (min-width: 750px) { .framer-UddiK .framer-styles-preset-1o2kbzs:not(.rich-text-wrapper), .framer-UddiK .framer-styles-preset-1o2kbzs.rich-text-wrapper h4 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 600; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 749px) and (min-width: 0px) { .framer-UddiK .framer-styles-preset-1o2kbzs:not(.rich-text-wrapper), .framer-UddiK .framer-styles-preset-1o2kbzs.rich-text-wrapper h4 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 600; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-UddiK";

// /:https://framerusercontent.com/modules/wmE787IEDtCo5j1urISQ/ksczH9YeZdCSOMnkAQ1p/yLuNtHpsx.js
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["ODdWXTHzJ", "ieo_AAQOn"];
var serializationHash = "framer-199I4";
var variantClassNames = {
	ieo_AAQOn: "framer-v-1ux6hxb",
	ODdWXTHzJ: "framer-v-ogeptw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	mobile: "ieo_AAQOn",
	Primary: "ODdWXTHzJ",
};
var getProps = ({
	discription1,
	discription2,
	height,
	id,
	title1,
	title2,
	width,
	...props
}) => {
	return {
		...props,
		HKg707RIG: title1 ?? props.HKg707RIG ?? "Senior Designer.",
		kLCshh1kV:
			discription1 ??
			props.kLCshh1kV ??
			"Experience and expertise at your fingertips, ensuring exceptional design quality.",
		lqrlZlvt0: title2 ?? props.lqrlZlvt0 ?? "Junior Designers.",
		qNAzsox6U:
			discription2 ??
			props.qNAzsox6U ??
			"Inexperienced designers may compromise on quality and attention to detail.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ODdWXTHzJ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		HKg707RIG,
		kLCshh1kV,
		lqrlZlvt0,
		qNAzsox6U,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ODdWXTHzJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ogeptw",
							className3,
							classNames,
						)}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"ODdWXTHzJ"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-cba3b9c8-9e49-437e-aca1-1e69db3088dc, rgb(17, 17, 17))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "inset 0px 2px 0px 0px rgba(92, 92, 92, 0.08)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								ieo_AAQOn: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-192rcxi"}
							data-framer-name={"Left card"}
							layoutDependency={layoutDependency}
							layoutId={"JPGBGil43"}
						>
							<motion.div
								className={"framer-jw1ig1"}
								data-framer-name={"check"}
								layoutDependency={layoutDependency}
								layoutId={"eEdTCTAB0"}
								style={{
									backgroundColor:
										"var(--token-b2b2cec5-8316-4f9c-8fd9-5fdfc3c24032, rgba(255, 255, 255, 0.1))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-x1vh7r-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"EShimKV6M-container"}
										nodeId={"EShimKV6M"}
										rendersWithMotion={true}
										scopeId={"yLuNtHpsx"}
									>
										<Icon
											color={
												"var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"Smiley"}
											id={"EShimKV6M"}
											layoutId={"EShimKV6M"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"bold"}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<motion.div
								className={"framer-15k48vk"}
								data-framer-name={"text content"}
								layoutDependency={layoutDependency}
								layoutId={"fxIPMYc7z"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1b2snmq"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Ok1uTLKoE"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={HKg707RIG}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1o2kbzs"}
											data-styles-preset={"HglFp_qS2"}
										>
											{"Senior Designer."}
										</motion.h4>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-90acd1"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"DuAcUNfjR"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										opacity: 0.7,
									}}
									text={kLCshh1kV}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-vp3sdo"}
											data-styles-preset={"WQG2SsoyY"}
										>
											{
												"Experience and expertise at your fingertips, ensuring exceptional design quality."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-jivcgr"}
							data-framer-name={"Line"}
							layoutDependency={layoutDependency}
							layoutId={"Wvo0E0GGv"}
							style={{
								backgroundColor:
									"var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))",
								opacity: 0.1,
							}}
						/>
						<motion.div
							className={"framer-125ryxn"}
							data-framer-name={"right card"}
							layoutDependency={layoutDependency}
							layoutId={"U_LRaxtOM"}
						>
							<motion.div
								className={"framer-1x71x2v"}
								data-framer-name={"check"}
								layoutDependency={layoutDependency}
								layoutId={"CcNDgtBYD"}
								style={{
									backgroundColor:
										"var(--token-b2b2cec5-8316-4f9c-8fd9-5fdfc3c24032, rgba(255, 255, 255, 0.1))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-18t1b1z-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"ce3lj5Mvf-container"}
										nodeId={"ce3lj5Mvf"}
										rendersWithMotion={true}
										scopeId={"yLuNtHpsx"}
									>
										<Icon
											color={
												"var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"Smiley"}
											id={"ce3lj5Mvf"}
											layoutId={"ce3lj5Mvf"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"bold"}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<motion.div
								className={"framer-18w7kwj"}
								data-framer-name={"text content"}
								layoutDependency={layoutDependency}
								layoutId={"f7RFP9EKT"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-33fdk6"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ugDKiyPN4"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={lqrlZlvt0}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1o2kbzs"}
											data-styles-preset={"HglFp_qS2"}
										>
											{"Junior Designers."}
										</motion.h4>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1dqrmpe"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"PfXmUcS_q"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										opacity: 0.7,
									}}
									text={qNAzsox6U}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-vp3sdo"}
											data-styles-preset={"WQG2SsoyY"}
										>
											{
												"Inexperienced designers may compromise on quality and attention to detail."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-199I4.framer-z1ro1o, .framer-199I4 .framer-z1ro1o { display: block; }",
	".framer-199I4.framer-ogeptw { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: wrap; gap: 50px; height: min-content; justify-content: center; overflow: visible; padding: 40px; position: relative; width: 1100px; }",
	".framer-199I4 .framer-192rcxi, .framer-199I4 .framer-125ryxn { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-199I4 .framer-jw1ig1, .framer-199I4 .framer-1x71x2v { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 6px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-199I4 .framer-x1vh7r-container, .framer-199I4 .framer-18t1b1z-container { flex: none; height: 17px; position: relative; width: 17px; }",
	".framer-199I4 .framer-15k48vk, .framer-199I4 .framer-18w7kwj { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-199I4 .framer-1b2snmq, .framer-199I4 .framer-90acd1, .framer-199I4 .framer-33fdk6, .framer-199I4 .framer-1dqrmpe { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-199I4 .framer-jivcgr { align-self: stretch; flex: none; height: auto; overflow: hidden; position: relative; width: 1px; }",
	".framer-199I4.framer-v-1ux6hxb.framer-ogeptw { flex-direction: column; gap: 24px; padding: 24px; }",
	".framer-199I4.framer-v-1ux6hxb .framer-192rcxi, .framer-199I4.framer-v-1ux6hxb .framer-125ryxn { flex: none; width: 100%; }",
	".framer-199I4.framer-v-1ux6hxb .framer-jivcgr { align-self: unset; height: 1px; width: 100%; }",
	...css2,
	...css,
];
var FrameryLuNtHpsx = withCSS(Component, css3, "framer-199I4");
var stdin_default = FrameryLuNtHpsx;
FrameryLuNtHpsx.displayName = "Benefit Card";
FrameryLuNtHpsx.defaultProps = {
	height: 238,
	width: 1100,
};
addPropertyControls(FrameryLuNtHpsx, {
	variant: {
		options: ["ODdWXTHzJ", "ieo_AAQOn"],
		optionTitles: ["Primary", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	HKg707RIG: {
		defaultValue: "Senior Designer.",
		displayTextArea: false,
		title: "Title 1",
		type: ControlType.String,
	},
	kLCshh1kV: {
		defaultValue:
			"Experience and expertise at your fingertips, ensuring exceptional design quality.",
		displayTextArea: false,
		title: "discription 1",
		type: ControlType.String,
	},
	lqrlZlvt0: {
		defaultValue: "Junior Designers.",
		displayTextArea: false,
		title: "Title 2",
		type: ControlType.String,
	},
	qNAzsox6U: {
		defaultValue:
			"Inexperienced designers may compromise on quality and attention to detail.",
		displayTextArea: false,
		title: "discription 2",
		type: ControlType.String,
	},
});
addFonts(
	FrameryLuNtHpsx,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:benefit-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ieo_AAQOn",
	xl: "ODdWXTHzJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0db2cec6a51bfbc819a58c52eb8c1d5df9643fd4922504e375a2cbd7f2ff2fa5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BenefitCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0db2cec6a51bfbc819a58c52eb8c1d5df9643fd4922504e375a2cbd7f2ff2fa5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var benefit_card_default = ComponentWithRoot;
export { benefit_card_default as default };
