// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0db2cec6a51bfbc8 "AM portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Closed' | 'Open' // Variant
 * question?: string // Question
 * answer?: string // Answer
}} Props

 */
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { className, css, fonts } from "./chunks/chunk-QT4ZEWLA.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-E5XEKSIV.js";
import { routes } from "./chunks/chunk-23HYNGZD.js";

// virtual:faq-single
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vFjYNCPvDiNnD5JSgF0c/pc2eAsu3ipWk5kerPH1P/oZAtms87i.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["Yy39wmVlB", "I2WSYs54m"];
var serializationHash = "framer-Nmbhd";
var variantClassNames = {
	I2WSYs54m: "framer-v-hlfizj",
	Yy39wmVlB: "framer-v-7zfi6p",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "Yy39wmVlB",
	Open: "I2WSYs54m",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		T8rQFvSBR:
			answer ??
			props.T8rQFvSBR ??
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Yy39wmVlB",
		W88zB8mIG:
			question ??
			props.W88zB8mIG ??
			"Is Framer is a web builder for creative pro?",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		W88zB8mIG,
		T8rQFvSBR,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Yy39wmVlB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapfkb397 = activeVariantCallback(async (...args) => {
		setVariant("I2WSYs54m");
	});
	const onTaps3b3zj = activeVariantCallback(async (...args) => {
		setVariant("Yy39wmVlB");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "I2WSYs54m") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-7zfi6p",
							className3,
							classNames,
						)}
						data-framer-name={"Closed"}
						layoutDependency={layoutDependency}
						layoutId={"Yy39wmVlB"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-cba3b9c8-9e49-437e-aca1-1e69db3088dc, rgb(17, 17, 17))",
							borderBottomLeftRadius: 15,
							borderBottomRightRadius: 15,
							borderTopLeftRadius: 15,
							borderTopRightRadius: 15,
							boxShadow:
								"16px 24px 20px 8px rgba(0, 0, 0, 0.4), inset 0px 2px 0px 0px rgba(184, 180, 180, 0.08)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								I2WSYs54m: {
									"data-framer-name": "Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-6j01z4"}
							data-framer-name={"Question"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"nxfrSccjW"}
							onTap={onTapfkb397}
							{...addPropertyOverrides(
								{
									I2WSYs54m: {
										onTap: onTaps3b3zj,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-uriyq0"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"NE7A8wUG0"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={W88zB8mIG}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-vp3sdo"}
										data-styles-preset={"WQG2SsoyY"}
									>
										{"Is Framer is a web builder for creative pro?"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-xqku8g-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"KJKv6qCkJ-container"}
									nodeId={"KJKv6qCkJ"}
									rendersWithMotion={true}
									scopeId={"oZAtms87i"}
									style={{
										rotate: 0,
									}}
									variants={{
										I2WSYs54m: {
											rotate: 45,
										},
									}}
								>
									<Icon
										color={
											"var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))"
										}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={"Plus"}
										id={"KJKv6qCkJ"}
										layoutId={"KJKv6qCkJ"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"bold"}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1ik48hs"}
								data-framer-name={"Answer"}
								layoutDependency={layoutDependency}
								layoutId={"d5Cg2I982"}
								style={{
									opacity: 0,
								}}
								variants={{
									I2WSYs54m: {
										opacity: 1,
									},
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-xaobjf"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lRundmW0E"}
									style={{
										opacity: 0.7,
									}}
									text={T8rQFvSBR}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-wu4ebp"}
											data-styles-preset={"H1YXoF4HR"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{
												"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Nmbhd.framer-bt0f2r, .framer-Nmbhd .framer-bt0f2r { display: block; }",
	".framer-Nmbhd.framer-7zfi6p { align-content: flex-start; align-items: flex-start; cursor: default; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 20px 0px 10px; position: relative; width: 561px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Nmbhd .framer-6j01z4 { -webkit-user-select: none; align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 25px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px; position: relative; user-select: none; width: 100%; }",
	".framer-Nmbhd .framer-uriyq0 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-Nmbhd .framer-xqku8g-container { flex: none; height: 15px; position: relative; width: 15px; }",
	".framer-Nmbhd .framer-1ik48hs { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 20px 0px 20px; position: relative; width: 100%; }",
	".framer-Nmbhd .framer-xaobjf { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Nmbhd.framer-7zfi6p, .framer-Nmbhd .framer-6j01z4, .framer-Nmbhd .framer-1ik48hs { gap: 0px; } .framer-Nmbhd.framer-7zfi6p > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-Nmbhd.framer-7zfi6p > :first-child, .framer-Nmbhd .framer-1ik48hs > :first-child { margin-top: 0px; } .framer-Nmbhd.framer-7zfi6p > :last-child, .framer-Nmbhd .framer-1ik48hs > :last-child { margin-bottom: 0px; } .framer-Nmbhd .framer-6j01z4 > * { margin: 0px; margin-left: calc(25px / 2); margin-right: calc(25px / 2); } .framer-Nmbhd .framer-6j01z4 > :first-child { margin-left: 0px; } .framer-Nmbhd .framer-6j01z4 > :last-child { margin-right: 0px; } .framer-Nmbhd .framer-1ik48hs > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } }",
	".framer-Nmbhd.framer-v-hlfizj.framer-7zfi6p { padding: 0px 20px 20px 10px; }",
	".framer-Nmbhd.framer-v-hlfizj .framer-6j01z4 { padding: 20px 20px 15px 20px; }",
	...css2,
	...css,
];
var FrameroZAtms87i = withCSS(Component, css3, "framer-Nmbhd");
var stdin_default = FrameroZAtms87i;
FrameroZAtms87i.displayName = "FAQ Single";
FrameroZAtms87i.defaultProps = {
	height: 67,
	width: 561,
};
addPropertyControls(FrameroZAtms87i, {
	variant: {
		options: ["Yy39wmVlB", "I2WSYs54m"],
		optionTitles: ["Closed", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	W88zB8mIG: {
		defaultValue: "Is Framer is a web builder for creative pro?",
		displayTextArea: true,
		title: "Question",
		type: ControlType.String,
	},
	T8rQFvSBR: {
		defaultValue:
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.",
		displayTextArea: true,
		title: "Answer",
		type: ControlType.String,
	},
});
addFonts(
	FrameroZAtms87i,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-single
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "I2WSYs54m",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0db2cec6a51bfbc819a58c52eb8c1d5df9643fd4922504e375a2cbd7f2ff2fa5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqSingleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0db2cec6a51bfbc819a58c52eb8c1d5df9643fd4922504e375a2cbd7f2ff2fa5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var faq_single_default = ComponentWithRoot;
export { faq_single_default as default };
